FROM golang:1.26-trixie AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
RUN CGO_ENABLED=0 go build -trimpath -o /usr/local/bin/relay ./cmd/relay

FROM debian:trixie-slim
RUN apt-get update && apt-get install -y iproute2 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/bin/relay /usr/local/bin/relay
COPY run-relay.sh /usr/local/bin/run-relay.sh
RUN chmod +x /usr/local/bin/run-relay.sh
ENTRYPOINT ["/usr/local/bin/run-relay.sh"]
