FROM golang:1.26-trixie AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd ./cmd
RUN CGO_ENABLED=0 go build -trimpath -o /usr/local/bin/peer ./cmd/peer

FROM debian:trixie-slim
RUN apt-get update && apt-get install -y iproute2 && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/bin/peer /usr/local/bin/peer
COPY run-peer.sh /usr/local/bin/run-peer.sh
RUN chmod +x /usr/local/bin/run-peer.sh
ENTRYPOINT ["/usr/local/bin/run-peer.sh"]
