System hostname = openbsd-router
Password for root account = foobarbaz
Public ssh key for root account = no
Network interfaces = vio0
IPv4 address for vio0 = autoconf
Setup a user = no
Allow root ssh login = no
Do you expect to run the X Window System = no
Change the default console to com0 = yes
Which speed should com0 use = 115200
Which disk is the root disk = sd0
Use (W)hole disk MBR, whole disk (G)PT, or (E)dit = W
Use (A)uto layout, (O)penBSD area or (E)dit = A
Location of sets = http
HTTP Server = 10.0.2.2
Server directory = pub/OpenBSD/7.8/amd64
Use sets found here anyway = yes
Set name(s) = +site78.tgz -game78.tgz -x* done
Continue without verification = yes
Checksum test for sets = skip
Timezone name = UTC
Reboot after installation = yes
